[package]
name = "rpm-rs"
version = "0.2.1"
authors = ["René Richter <richterrettich@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A pure rust library for building and parsing RPM's"

homepage = "https://github.com/Richterrettich/rpm-rs"
repository = "https://github.com/Richterrettich/rpm-rs"

readme = "README.md"

keywords = ["RPM", "packaging"]

categories = ["parsing", "development-tools"]

[lib]
name="rpm"
path="src/rpm.rs"

[dependencies]
nom = "5.0.0"
num-traits = "0.2"
num-derive = "0.2"
num = "0.2.0"
enum-display-derive = "0.1.0"
cpio = "0.2.0"
libflate = "0.1.23"
sha2 = "0.8.0"
md-5 = "0.8.0"
sha1 = "0.6.0"
tokio = "0.1.11"
